version = 0.1
[ojaysanya]
[ojaysanya.deploy]
[ojaysanya.deploy.parameters]
stack_name = "sam-app-user1-dev-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1crbfqx4rb73h"
s3_prefix = "sam-app-user1-dev-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
